### ISSUE TITLE
MAM+Carbons creates a shadow conversation with myself

### ISSUE THREAD

**Issue by Aeyoun** [anurodhp/Monal#13]
Version 1.2 (24) from MAS, OS X 10.11.3.

User B sends me a message, I reply to it on another devices.

Monal will then show one active conversation with User B with their and my messages in it. I’ll also get a second active conversation in Monal that only includes my own messages sent to User B from my second device,

**Comment by anurodhp** [comment]
this should be fixed in the latest OS X beta.

**Comment by anurodhp** [comment]
fixed in next iOS release as well.

**Comment by ge0rg** [comment]
This problem is still existing in iOS build 2.9.3. I see two active chats with "contact@yax.im" and "myself@yax.im" and all carbon messages from my other client show up in both chats as received messages, not as sent messages.
